name: XCode tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      
      - name: Run Tests on iPhone Simulator
        run: |
          cd src/iOS
          xcodebuild test \
            -scheme GoMapTests \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -allowProvisioningUpdates 
          xcodebuild test \
            -scheme GoMapUITests \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -allowProvisioningUpdates 
