name: XCode tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.10.1"

      - name: Get swift version
        run: swift --version
            
      - name: Run Tests on iPhone Simulator
        run: |
          cd src/iOS
          xcodebuild test \
            -scheme GoMapTests \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -allowProvisioningUpdates 
          xcodebuild test \
            -scheme GoMapUITests \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -allowProvisioningUpdates 
